sudo: required
dist: trusty

#install google chrome, using addons
addons:
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable

language: node_js
node_js:
  - "6"

deploy:
  skip_cleanup: true
  provider: npm
  email: ps00552515@techmahindra.com, shukla.priyavrat@gmail.com

before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - npm install gulp-cli
  

script: gulp test:ci

after_success: gulp coveralls

cache:
  yarn: true
  