sudo: required
dist: trusty

#install google chrome, using addons
addons:
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable

language: node_js
node_js:
  - "6"

before_install:
# Install the Node version to test against
- nvm install 8.0.0
# Switch back to build-time Node version
- nvm use 8.0.0

before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - npm install --quiet -g gulp-cli
  

script: gulp test:ci

after_success: gulp coveralls

cache:
  yarn: true
  